# Generated by Django 4.1.2 on 2022-10-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('id_classe', models.IntegerField()),
                ('id_naturel_it', models.IntegerField()),
                ('id_pays', models.IntegerField()),
                ('nature_client', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('id_categorie_avoir', models.IntegerField()),
                ('raison_sociale', models.IntegerField()),
                ('matricule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComptesEspece',
            fields=[
                ('id_compte', models.IntegerField(primary_key=True, serialize=False)),
                ('id_depositaire', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('web', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=50)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ImputationsEspeces',
            fields=[
                ('id_imputation', models.IntegerField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('sens', models.BooleanField()),
                ('date_imputation', models.DateTimeField()),
                ('id_date_imputation', models.IntegerField()),
                ('id_sdb_compte', models.IntegerField()),
                ('date_valeur', models.DateTimeField()),
                ('nature', models.CharField(max_length=50)),
                ('etat', models.IntegerField()),
                ('date_etat', models.IntegerField()),
                ('libelle', models.CharField(choices=[('CHQU', 'CHQU'), ('VIREMENT', 'VIREMENT')], max_length=10)),
                ('id_compte_espece', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.comptesespece')),
            ],
        ),
    ]
